### ISSUE TITLE
versions of R and RStudio

### ISSUE THREAD

**Issue by ajstewartlang** [carpentries-incubator/statistical-thinking-public-health#1]
Might it be worth specifying a minimum version of R and RStudio (and possibly even packages) given changes to things like `read_csv()` in the context of `stringasfactors` in the `tidyverse` and changes to (e.g.) randomisation in base R?  And I see R 4.1 seems to have broken some aspects of the previous version of RStudio. One possibility would be to list the configuration on your own machine Ezra which you used to create the lesson content.

**Comment by ezherman** [comment]
Hi @ajstewartlang, that's a good point. The link on the home page refers students to set-up instructions for the latest versions of R and RStudio. Do you think it would be sufficient to ask that students have the latest versions installed? I'm not sure how to figure out what the minimum versions of R and RStudio would be.

**Comment by ajstewartlang** [comment]
I think the latest versions should be fine- but maybe have somewhere mention of what version of R and RStudio you used for the material - if it's R 3.6 or above then all should be fine in terms of the randomisation algorithm

**Comment by ezherman** [comment]
Sounds good! I have included a note under Extras -> Instructor Notes.
