### ISSUE TITLE
Estimating the variation around the mean: standard errors and confidence intervals: typo

### ISSUE THREAD

**Issue by 3mmaRand** [carpentries-incubator/statistical-thinking-public-health#10]
https://carpentries-incubator.github.io/statistical-thinking-public-health/02-estimation/index.html

There are a couple of incorrect variables in the Simulating 95% confidence intervals challenge solution. They are in the data generation loop. seBP has been used instead of bloodPressure and stdErr were it should be seBP

It should be

for(i in 1:100){
  sample <- tibble(bloodPressure = rnorm(2000, mean = 112, sd = 10))
  means <- means %>%
    add_row(sampleID = i,
            meanBP = mean(sample$bloodPressure),
            lower_CI = mean(sample$bloodPressure) - 1.96 * seBP,
            upper_CI = mean(sample$bloodPressure) + 1.96 * seBP)
}

**Comment by ezherman** [comment]
Thanks @3mmaRand, fixed!
