### ISSUE TITLE
small word change in associations episode

### ISSUE THREAD

**Issue by corybrunson** [carpentries-incubator/statistical-thinking-public-health#14]
Hello! I was glad to see your public health lessons in the incubator and will be interested to follow their development. Thank you for putting them together.

I want to suggest a word change, from "for which" to "for whom" on line 94 of `03-association.Rmd`, to help personalize the participants.

I also want to ask if the preference is for even such minor changes to be suggested as issues rather than as pull requests. (The CONTRIBUTING guidelines are clear but seem written for the more established core lessons.)

**Comment by ezherman** [comment]
Hi @corybrunson, thank you for your interest! Apologies for the late reply - my annual leave had just started when you opened this issue. 

Following your comments, I have changed the wording and edited the contributing guidelines. Thanks for bringing the guidelines to my attention - I had not thought of editing these.

As for suggesting edits of minor changes: for one change an issue is fine, but for multiple changes (e.g. multiple spelling errors) I would prefer a pull request. 

If you have any further questions about the development and/or teaching of these lessons, feel free to drop me a message!

**Comment by corybrunson** [comment]
@ezherman thanks very much! I hope and intend to contribute more in future, and i will feel welcome to contact you if appropriate.
