### ISSUE TITLE
1.96 magic number could be explained more clearly

### ISSUE THREAD

**Issue by alanocallaghan** [carpentries-incubator/statistical-thinking-public-health#16]
It's not clear why it's 1.96, intuitively for a 95% CI 1.95 might make sense. Easy to get into the weeds with this stuff but at the moment it's introduced with no explanation

**Comment by ezherman** [comment]
Hi @Alanocallaghan, this is a good point. Perhaps it would be best to cover this in a callout box. I will set aside some time to look into this.

**Comment by alanocallaghan** [comment]
Yes probably best for a callout box, as it's not really crucial to gain the intuition, but can be a bit confusing if you ponder on it. Somebody brought it up in chat
