### ISSUE TITLE
Independent/dependent terminology not introduced

### ISSUE THREAD

**Issue by alanocallaghan** [carpentries-incubator/statistical-thinking-public-health#19]
Dependent/independent isn't introduced in the lesson but you used it while speaking

Also this is possibly a prickly subject but I dislike dependent/independent terminology and prefer something like "predictor and outcome" as this is more colloquial

**Comment by ezherman** [comment]
Hi Alan, I believe there was a sentence about this in episode 4. However, it's quite possible that I forgot to cover the terminology verbally! I edited the text to include predictor and outcome as well.
