### ISSUE TITLE
set.seed() doesn't echo

### ISSUE THREAD

**Issue by ajstewartlang** [carpentries-incubator/statistical-thinking-public-health#2]
If someone were to type the code using `rnorm` they wouldn't get the same output as in the lesson (and may be confused). I see that `set.seed()` is in the code chunk, but doesn't echo to the knitted file. Might be worth letting people see that line of code but also explaining what it's for - i.e., as computers can't generate truly random numbers we set the seed of the randomisation algorithm to ensure that when we rerun any code that requires the use of random numbers, we always get the same result.

**Comment by ajstewartlang** [comment]
Actually, I think is important throughout as there are several places where `rnorm()` is used - which will produce a different result for people depending on the randomisation seed - getting results from the lesson content could be confusing.

**Comment by ezherman** [comment]
Hi @ajstewartlang, my thinking here was that this is an opportunity for students to see random sampling in action. Two students running the code would get different results, just as they would if they replicated an experiment in parallel. I could state this more explicitly in the text to avoid confusion. Do you agree that they might learn more from that than if they all got the same result by fixing the seed?

This also relates to issue #3 on 95% CIs. In the long run, 95% of 95% CIs will contain the population mean. But when drawing 100 samples, there is variation in the number of CIs that cover the population mean. This is why I thought it would actually be insightful to see only 2 CIs not covering the population mean in the lesson. Again, maybe this should be explained more clearly in the main body. In my mind, at the workshop, students would get different proportions but at the class level it would be close to 95%.

**Comment by ajstewartlang** [comment]
Totally agree - just make this explicit in the text I think - just to avoid the case where they might think they have done something 'wrong' if they get a different output to the one in the material or different from their neighbour.

**Comment by ezherman** [comment]
Sounds good, I've made it more explicit now! We'll see at the workshop whether students follow the reasoning or that it requires more explanation.
