### ISSUE TITLE
Unnecessary Tibble?

### ISSUE THREAD

**Issue by nathansam** [carpentries-incubator/statistical-thinking-public-health#27]
On this page, we create a tibble (sample) of one variable (heights) in a for loop which we only access to extract the heights. Does it make sense to drop the tibble function and just assign to an object straight from rnorm like sample <- rnorm()? It avoids confusion with the other tibble we are working with (means) and just seems simpler to me. 

``` R
for(i in 1:100){
 sample <- tibble(heights = rnorm(1000, mean = 162, sd = 6.89))
 
 means <- means %>%
   add_row(sampleID = i,
           meanHeight = mean(sample$heights),
           seHeight = sd(sample$heights)/sqrt(1000),
           lower_CI = meanHeight - 1.96 * seHeight,
           upper_CI = meanHeight + 1.96 * seHeight)
}
```

https://carpentries-incubator.github.io/statistical-thinking-public-health/02-estimation/index.html

**Comment by ezherman** [comment]
Thanks Nathan, that's indeed simpler!
