### ISSUE TITLE
Change the color red to magenta in ggplot images

### ISSUE THREAD

**Issue by ggrimes** [carpentries-incubator/statistical-thinking-public-health#28]
In two episodes the colour red is used to high light features in the plot.
To make the plot accessible to those with colour blindness this should be changed to magenta, as dark red on black in difficult to distinguish  .

**Comment by ezherman** [comment]
Thanks for pointing this out Graeme. I will be making edits to the materials soon, so I will make sure to change the colour of the lines then.
