### ISSUE TITLE
95% CIs

### ISSUE THREAD

**Issue by ajstewartlang** [carpentries-incubator/statistical-thinking-public-health#3]
I wonder in this lesson (https://carpentries-incubator.github.io/statistical-thinking-public-health/02-estimation/index.html) where this "95% of 95% confidence intervals are expected to contain the true population mean" could be a bit confusing in the context of the data simulation - where I think it's actually 98 out of 100 cases in the simulation. Would "roughly 95% of 95% confidence intervals are expected to contain the true population mean" be better - and maybe again clarify this approximation after the results of the simulation are presented?

**Comment by ezherman** [comment]
Hi @ajstewartlang, I hope that my clarification in-text has made the definition of the 95% CI clearer. I am hesitant to include "roughly" in the definition, as it is not an approximation.  But I did include "approximately" in the text, where I refer specifically to 100 samples. Then there is a further clarification towards the end of the episode, after 100 CIs are plotted. Do you think it's sufficiently clear now?
