### ISSUE TITLE
where does the `dat` tibble come from?

### ISSUE THREAD

**Issue by ajstewartlang** [carpentries-incubator/statistical-thinking-public-health#4]
I wasn't quite sure in lesson (https://carpentries-incubator.github.io/statistical-thinking-public-health/03-association/index.html) where the `dat` tibble came from - is it a built-in one?

**Comment by ajstewartlang** [comment]
Also, should weights and heights have units in the plot?

**Comment by ezherman** [comment]
Hi @ajstewartlang, I have now included a note that `dat` is obtained by following the setup.

I have left out making the plots "pretty", including the inclusion of units, to reduce the cognitive load for students. I imagine many won't be fluent in `ggplot2`, so those extra steps might take away from the key points of the episode. What do you think?
