### ISSUE TITLE
is NHANES mapped onto `dat`?

### ISSUE THREAD

**Issue by ajstewartlang** [carpentries-incubator/statistical-thinking-public-health#5]
In https://carpentries-incubator.github.io/statistical-thinking-public-health/04-prediction/index.html I think it looks like NHANES is mapped onto the `dat`variable - the text refers to NHANES, but the code to `dat` so it's not entirely clear as to whether these are the same datasets.

**Comment by ajstewartlang** [comment]
In this lesson is it also worth having one line explaining what `drop_na()` is doing?

**Comment by ajstewartlang** [comment]
Might be worth ensuring consistency of writing `Height` and `Weight` in title case across both code and narrative.

**Comment by ajstewartlang** [comment]
> In https://carpentries-incubator.github.io/statistical-thinking-public-health/04-prediction/index.html I think it looks like NHANES is mapped onto the `dat`variable - the text refers to NHANES, but the code to `dat` so it's not entirely clear as to whether these are the same datasets.

I totally missed the bit in the setup where this is covered!

**Comment by ezherman** [comment]
Hi @ajstewartlang, good shout about `drop_na()`. I will include a line. I've also corrected the case for Height and Weight in-text.
