### ISSUE TITLE
Estimating the mean, variance and standard deviation

### ISSUE THREAD

**Issue by 3mmaRand** [carpentries-incubator/statistical-thinking-public-health#6]
https://carpentries-incubator.github.io/statistical-thinking-public-health/01-describeVariable/index.html

I like the simulation approach through out.

As a definition for a distribution I like: A variable will follow a distribution, which shows the values a variable can take and their chances of occuring.

I quite like not using set.seed() in this situation (where part of what you're demonstrating is random samples). Add notes (in the example and challenge solution) to repeat that they should expect similar but different values those those you have. You might suggest they ask their neighbour what their mean/sd are.

**Comment by ezherman** [comment]
Final comment in this issue resolved through commit d764976.
